# See original blog post
# https://medium.com/@vitalypanukhin/docker-compose-and-gitlab-b209d09210f6
#
# NOTE: Don't worry, it can take a few days really understand this file,
#       as you need to understand:
#         - gitlab-ci.yml (+ its workers and env)
#         - ssh + private/public keys
#         - docker compose + containers
#         - provisioninng computing units from cloud providers like AWS, GCP, DigitalOcean, ...
#
# Find more about .gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/yaml/gitlab_ci_yaml.html
#
# Authentication:
# Note on the "user" that authenticates with docker and pushes
# the image to repository:
#
# - Original blog post named it `gitlab-ci-token`, which is how
#   they named the Deploy Token. However, in the screenshot in
#   the blog post, the token doesn't have correct permissions.
#
# - I assume the Deploy Token needs both `read_registry` and
#   `write_registry`, because:
#   1) We push to registry on build and release jobs
#   2) We pull from the registry on stage/prod deploys
#
# - There are several types of deploy tokens / auth methods.
#   we use the fact that if deploy token is called `gitlab-deploy-token`,
#   then in CI the env vars CI_DEPLOY_USER and CI_DEPLOY_PASSWORD
#   are populated with its info.
#
# Learn more:
# - https://docs.gitlab.com/ee/user/project/deploy_tokens/index.html#gitlab-deploy-token
# - https://docs.gitlab.com/ee/user/packages/container_registry/authenticate_with_container_registry.html
# - https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html
#
# Troubleshooting
# - SSH
#   - https://stackoverflow.com/questions/1405324
#   - https://serverfault.com/questions/638628
#   - https://pentestmonkey.net/blog/ssh-with-no-tty
# - SSH + docker-compose
#   - NOTE: using `docker-compose -H "ssh://...` did not work
#   - https://stackoverflow.com/questions/66548612
#   - https://github.com/docker/compose/issues/9852
#   - https://stackoverflow.com/questions/4135261/paramiko-authenticationexception-issue

########################
# 1. SETUP
########################

image: creatiwww/docker-compose:latest

services:
  ## See https://forum.gitlab.com/t/why-services-docker-dind-is-needed-while-already-having-image-docker/43534
  - docker:dind

variables:
  # SERVER_IP_STAGE: 10.10.10.1
  SERVER_IP_PROD: 10.10.10.2
  # SERVER_USER_STAGE: gitlab
  SERVER_USER_PROD: gitlab
  ## Tags used for deployment
  ## E.g. registry.gitlab.com/org-name/proj-name/server-dev:latest
  SERVER_TAG_LATEST: $CI_REGISTRY_IMAGE/server-$CI_COMMIT_REF_NAME:latest
  ## E.g. registry.gitlab.com/org-name/proj-name/server-dev:526490c1
  SERVER_TAG_COMMIT: $CI_REGISTRY_IMAGE/server-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  ## E.g. registry.gitlab.com/org-name/proj-name/server-dev:latest
  CRON_TAG_LATEST: $CI_REGISTRY_IMAGE/cron-$CI_COMMIT_REF_NAME:latest
  ## E.g. registry.gitlab.com/org-name/proj-name/server-dev:526490c1
  CRON_TAG_COMMIT: $CI_REGISTRY_IMAGE/cron-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - test
  # - build-stg
  # - deploy-stg
  - build-prod
  - deploy-prod

########################
# 2.1 TEST JOBS
########################

# Test that we can establish connection to servers

# server-ssh-stg:
#   stage: test
#   only:
#     - staging
#   script:
#     - eval $(ssh-agent -s)
#     ## See https://stackoverflow.com/a/56163560/9788634
#     - echo "$GITLAB_CI_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#     ## Fix this issue https://codeql.github.com/codeql-query-help/python/py-paramiko-missing-host-key-validation/
#     ## https://www.techrepublic.com/article/how-to-easily-add-an-ssh-fingerprint-to-your-knownhosts-file-in-linux/
#     - mkdir ~/.ssh && ssh-keyscan -H $SERVER_IP_STAGE >> ~/.ssh/known_hosts
#     ## See https://serverfault.com/q/638628/1021637
#     - ssh -vT "$SERVER_USER_STAGE@$SERVER_IP_STAGE"

server-ssh-prod:
  stage: test
  only:
    - main
  script:
    - eval $(ssh-agent -s)
    ## See https://stackoverflow.com/a/56163560/9788634
    - echo "$GITLAB_CI_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    ## Fix this issue https://codeql.github.com/codeql-query-help/python/py-paramiko-missing-host-key-validation/
    ## https://www.techrepublic.com/article/how-to-easily-add-an-ssh-fingerprint-to-your-knownhosts-file-in-linux/
    - mkdir ~/.ssh && ssh-keyscan -H $SERVER_IP_PROD >> ~/.ssh/known_hosts
    ## See https://serverfault.com/q/638628/1021637
    - ssh -vT "$SERVER_USER_PROD@$SERVER_IP_PROD"

# Test code

server-lint:
  stage: test
  only:
    - staging
    - main
    - dev
  image: node:18-alpine
  script:
    - cd server
    - npm ci
    - npm run lint

server-test-unit:
  stage: test
  only:
    - staging
    - main
    - dev
  image: node:18-alpine
  script:
    - cd server
    - npm ci
    - npm run test:unit

########################
# 2.2 STAGE DEPLOY JOBS
########################

# server-build-stg:
#   stage: build-stg
#   only:
#     - staging
#   script:
#     - cd server
#     - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY_IMAGE
#     - mv .env.dev .env
#     - echo -e "\nNODE_SERVER_IMAGE_TAG=$SERVER_TAG_COMMIT" >> .env
#     - echo -e "\nCRON_IMAGE_TAG=$CRON_TAG_COMMIT" >> .env
#     - echo -e "\nMAIL_RELAY_PASSWORD=$MAIL_RELAY_PASSWORD" >> .env
#     - docker-compose build
#     - docker-compose push
#     - echo Image $SERVER_TAG_COMMIT added to registry $CI_REGISTRY_IMAGE

# server-deploy-stg:
#   stage: deploy-stg
#   only:
#     - staging
#   script:
#     - cd server
#     - mv .env.dev .env
#     - echo -e "\nNODE_SERVER_IMAGE_TAG=$SERVER_TAG_COMMIT" >> .env
#     - echo -e "\nCRON_IMAGE_TAG=$CRON_TAG_COMMIT" >> .env
#     - echo -e "\nMAIL_RELAY_PASSWORD=$MAIL_RELAY_PASSWORD" >> .env
#     - echo -e "\nAWS_S3_BACKUP_DB_KEY=$AWS_S3_BACKUP_DB_STAGE_KEY" >> .env
#     - echo -e "\nAWS_S3_BACKUP_DB_PWD=$AWS_S3_BACKUP_DB_STAGE_PWD" >> .env
#     - echo -e "\nSERVER_DB_PWD=$SERVER_DB_PWD_STAGE" >> .env
#     - |
#       # Load vars from .env
#       export $(grep -v '^#' .env | xargs)
#       # Add SERVER_DB_URL if it's not defined
#       if [ -z "$SERVER_DB_URL" ]; then
#         # E.g. postgres://user:pwd@postgres:5432/db_name?schema=public
#         echo -e "\nSERVER_DB_URL=postgres://${SERVER_DB_USER}:${SERVER_DB_PWD}@postgres:5432/${SERVER_DB_NAME}?schema=public" >> .env
#       fi
#     - eval $(ssh-agent -s)
#     - echo "$GITLAB_CI_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#     - mkdir ~/.ssh && ssh-keyscan -H $SERVER_IP_STAGE >> ~/.ssh/known_hosts
#     ## NOTE: using `docker-compose -H "ssh://...` did not work
#     ##       Instead, we manually copy files to server, SSH in, and run docker-compose
#     - scp -r .env docker-compose.yaml Dockerfile cron mailserver.env scripts volumes $SERVER_USER_STAGE@$SERVER_IP_STAGE:~
#     - |
#       ssh $SERVER_USER_STAGE@$SERVER_IP_STAGE "
#         docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY_IMAGE;
#         docker-compose down --remove-orphans;
#         docker-compose pull;
#         docker-compose up -d;
#         docker system prune -a -f;
#         docker volume prune -f;"

# server-restore-db-stg:
#   stage: deploy-stg
#   only:
#     - staging
#   when: manual
#   script:
#     - cd server
#     - eval $(ssh-agent -s)
#     - echo "$GITLAB_CI_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#     - mkdir ~/.ssh && ssh-keyscan -H $SERVER_IP_STAGE >> ~/.ssh/known_hosts
#     # Connect to server then connect to cron container to run db restore script
#     # The DB version to which the db will be restored is set via
#     # $SERVER_DB_RESTORE_FILE_STAGE in Gitlab CI/CD variables
#     - ssh $SERVER_USER_STAGE@$SERVER_IP_STAGE "docker exec cron /bin/bash -c \"/etc/supercronic/scripts/postgres-backup.sh restore $SERVER_DB_RESTORE_FILE_STAGE\""

########################
# 2.2 PROD DEPLOY JOBS
########################

server-build-prod:
  stage: build-prod
  only:
    - main
  script:
    - cd server
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY_IMAGE
    - mv .env.prd .env
    - echo -e "\nNODE_SERVER_IMAGE_TAG=$SERVER_TAG_LATEST" >> .env
    - echo -e "\nCRON_IMAGE_TAG=$CRON_TAG_LATEST" >> .env
    - docker-compose build
    - docker-compose push
    - echo Image $SERVER_TAG_LATEST added to registry $CI_REGISTRY_IMAGE

server-deploy-prod:
  stage: deploy-prod
  only:
    - main
  when: manual
  script:
    - cd server
    - mv .env.prd .env
    - echo -e "\nNODE_SERVER_IMAGE_TAG=$SERVER_TAG_LATEST" >> .env
    - echo -e "\nCRON_IMAGE_TAG=$CRON_TAG_LATEST" >> .env
    - echo -e "\nMAIL_RELAY_PASSWORD=$MAIL_RELAY_PASSWORD" >> .env
    - echo -e "\nAWS_S3_BACKUP_DB_KEY=$AWS_S3_BACKUP_DB_KEY_PROD" >> .env
    - echo -e "\nAWS_S3_BACKUP_DB_PWD=$AWS_S3_BACKUP_DB_PWD_PROD" >> .env
    - echo -e "\nSERVER_DB_PWD=$SERVER_DB_PWD_PROD" >> .env
    - |
      # Load vars from .env
      export $(grep -v '^#' .env | xargs)
      # Add SERVER_DB_URL if it's not defined
      if [ -z "$SERVER_DB_URL" ]; then
        # E.g. postgres://user:pwd@postgres:5432/db_name?schema=public
        echo -e "\nSERVER_DB_URL=postgres://${SERVER_DB_USER}:${SERVER_DB_PWD}@postgres:5432/${SERVER_DB_NAME}?schema=public" >> .env
      fi
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir ~/.ssh && ssh-keyscan -H $SERVER_IP_PROD >> ~/.ssh/known_hosts
    ## NOTE: using `docker-compose -H "ssh://...` did not work
    ##       Instead, we manually copy files to server, SSH in, and run docker-compose
    - scp -r .env docker-compose.yaml Dockerfile cron mailserver.env scripts volumes $SERVER_USER_PROD@$SERVER_IP_PROD:~
    - |
      ssh $SERVER_USER_PROD@$SERVER_IP_PROD "
        docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY_IMAGE;
        docker-compose down --remove-orphans;
        docker-compose pull;
        docker-compose up -d;
        docker system prune -a -f;
        docker volume prune -f;"

server-restore-db-prod:
  stage: deploy-prod
  only:
    - main
  when: manual
  script:
    - cd server
    - eval $(ssh-agent -s)
    - echo "$GITLAB_CI_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir ~/.ssh && ssh-keyscan -H $SERVER_IP_PROD >> ~/.ssh/known_hosts
    # Connect to server then connect to cron container to run db restore script
    # The DB version to which the db will be restored is set via
    # $SERVER_DB_RESTORE_FILE_PROD in Gitlab CI/CD variables
    - ssh $SERVER_USER_PROD@$SERVER_IP_PROD "docker exec cron /bin/bash -c \"/etc/supercronic/scripts/postgres-backup.sh restore $SERVER_DB_RESTORE_FILE_PROD\""
