########################
# 2.2 STAGE DEPLOY JOBS
########################

# server-db-restore-stg:
#   only:
#     - staging
#   when: manual
#   image: gotechnies/alpine-ssh
#   script:
#     - sh ./scripts/gitlab-ci.sh server-db-restore-stg

########################
# 2.2 PROD DEPLOY JOBS
########################

server-db-restore-prod:
  only:
    - main
  when: manual
  image: gotechnies/alpine-ssh
  script:
    - sh ./scripts/gitlab-ci.sh server-db-restore-prod
