
/* eslint-disable */
/* This file is autogenerated, see codegen.ts */

      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {
    "Connection": [],
    "Edge": []
  }
};
      export default result;
    
// Generated on 2023-06-15T22:37:12+02:00
